version: '3.9'

services:
  mongodb:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  ollama:
    image: ollama/ollama:0.1.34
    command: serve
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_MODELS=llama3 mistral phi3
    dns:
      - 8.8.8.8
      - 1.1.1.1

  backend:
    build: ./backend
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: mydb
      MONGO_COLLECTION: user_input
      OLLAMA_HOST: ollama
      OLLAMA_PORT: 11434
    depends_on:
      - mongodb
      - ollama
    ports:
      - "5001:5000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  mongo_data:
  ollama_data:
